#!/home/kimkk/miniconda3/envs/lomin/bin/python

import os
import argparse

import torch
import torch.onnx

from maskrcnn_benchmark.config import cfg

# detection model conf and weight file names
detect_model = {
        "v1":
        {
            "config_file": "config_det_v1_200723_001_180k.yaml",
            "weight_file": "model_det_v1_200723_001_180k.pth"

        },
        "v2":
        {
            "config_file": "config_det_v2_200924_002_180k.yaml",
            "weight_file": "model_det_v2_200924_002_180k.pth"
        }
}


if __name__ == '__main__':

    # command line arguments definition
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter,
                                     description="Lomin OCR detection model cfg printer")

    parser.add_argument('--version', choices=['v1', 'v2'], default='v2',
                        help='set detection model version')

    parser.add_argument('--output', required=True, help='file path for output')

    # command line argument parsing
    args = parser.parse_args()
    version = args.version

    # set model conf file path and mode weight file path
    # prefixed by ./model/[detection|recognition]
    config_file = os.path.join('model/detection', detect_model[version]["config_file"])
    weight_file = os.path.join('model/detection', detect_model[version]["weight_file"])


    # clone project level config and merge with experiment config
    cfg = cfg.clone()
    cfg.merge_from_file(config_file)

    with open(args.output, "w") as f:
        print(f"# {'-'*50}", file=f )

        # script file name
        print(f"# generated by '{os.path.basename(__file__)}'", file=f )
        print(f"# {'-'*50}", file=f )

        print(f"# Detection Model {version}", file=f )
        print(f"# - config file path:\n#   {config_file}", file=f)
        print(f"# - weight file path:\n#   {weight_file}", file=f)
        print(f"# {'-'*50}\n", file=f )

        print(f"{cfg}", file=f)



