INPUT:
  RESIZE_MODE: 'horizontal_padding'
  FIXED_SIZE: (128, 32)
  PIXEL_MEAN: [0.0, 0.0, 0.0]
  TO_BGR255: False
  TO_N1P1: True
MODEL:
  META_ARCHITECTURE: "TextRecognizer"
  BACKBONE:
    CONV_BODY: "TIMM-MOBILENETV2-100"
    FREEZE_CONV_BODY_AT: -1
  TIMM:
    BACKBONE_OUT_CHANNELS: 32
    OUT_INDICES: (2,)
  RECOGNITION: True
  TEXT_RECOGNIZER:
    CHARACTER: ("num", "eng_cap", "eng_low", "kor_2350", "symbols")
    BATCH_MAX_LENGTH: 10
    CNN_CHANNELS: 32
    CNN_NUM_POOLING: 3
    TRANSFORMER_FSIZE: 512
    TRANSFORMER_MODULE_NO: 1
    TRANSFORMER_NO_RECURRENT_PATH: True
    USE_PROJECTION: False
    OUTCONV_KS: (4, 1)
DATALOADER:
  SIZE_DIVISIBILITY: 0
TEST:
  IMS_PER_BATCH: 64

