INPUT:
  RESIZE_MODE: 'horizontal_padding'
  FIXED_SIZE: (128, 32) 
  PIXEL_MEAN: [0.0, 0.0, 0.0]
  TO_BGR255: False
  TO_N1P1: True
MODEL:
  META_ARCHITECTURE: "TextRecognizer"
  BACKBONE:
    CONV_BODY: "TIMM-MOBILENETV2-100"
  TIMM:
    BACKBONE_OUT_CHANNELS: 256
    OUT_INDICES: (2,)
  RPN:
    USE_FPN: True
  RECOGNITION: True
  TEXT_RECOGNIZER:
    CHARACTER: ("num", "eng_cap", "eng_low", "kor_2350", "symbols")
    BATCH_MAX_LENGTH: 10
    CNN_CHANNELS: 256
    CNN_NUM_POOLING: 2
    TRANSFORMER_FSIZE: 512
    TRANSFORMER_MODULE_NO: 1
    USE_PROJECTION: True
TEST:
  IMS_PER_BATCH: 512

